const KEY='apexFenceCRM.v1';const defaultData={leads:[],jobs:[],estimates:[],settings:{laborRate:45,serviceCharge:175,materialMarkup:25,homeDepotMarkup:50,woodPost14:125,woodPost5:100,quikrete:10, bagsPerPost:1,woodRepairLF:25,reinstallLF:10,picketAmerican:8.21,railAmerican:14.47,postAmerican:48.69}};let data=load();let deferredInstall=null;
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}'),settings:{...defaultData.settings,...(JSON.parse(localStorage.getItem(KEY)||'{}').settings||{})}}}catch{return structuredClone(defaultData)}}function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function $(id){return document.getElementById(id)}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo(0,0)}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v)showView(v.dataset.view);const a=e.target.closest('[data-action]');if(a){if(a.dataset.action==='new-lead')openLead();if(a.dataset.action==='new-job')openJob()}});
function renderDashboard(){const counts={};data.leads.forEach(x=>counts[x.status]=(counts[x.status]||0)+1);$('stats').innerHTML=[['Leads',data.leads.length],['Estimates',data.estimates.length],['Open Jobs',data.jobs.filter(x=>x.status!=='Complete').length],['Won',data.leads.filter(x=>x.status==='Won'||x.status==='Scheduled'||x.status==='Complete').length]].map(x=>'<div class="stat"><small>'+x[0]+'</small><strong>'+x[1]+'</strong></div>').join('');$('pipeline').innerHTML=['New','Contacted','Estimate Scheduled','Estimate Sent','Won','Scheduled','Complete','Lost'].map(s=>'<div class="pipeline-row"><span>'+s+'</span><strong>'+(counts[s]||0)+'</strong></div>').join('');const jobs=[...data.jobs].filter(x=>x.status!=='Complete').sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(0,5);$('upcoming').innerHTML=jobs.length?jobs.map(jobHTML).join(''):'<p class="muted">No upcoming jobs.</p>'}
function renderLeads(){const q=($('leadSearch')?.value||'').toLowerCase(),f=$('leadFilter')?.value||'all';const list=data.leads.filter(x=>(f==='all'||x.status===f)&&[x.name,x.phone,x.address,x.jobType].join(' ').toLowerCase().includes(q));$('leadList').innerHTML=list.length?list.map(leadHTML).join(''):'<div class="card"><p class="muted">No leads yet. Add your first customer.</p></div>'}
function leadHTML(x){return '<div class="lead"><div class="lead-top"><div><div class="lead-name">'+esc(x.name)+'</div><div class="mutedline">'+esc(x.phone||'')+' · '+esc(x.address||'')+'</div><div class="mutedline">'+esc(x.jobType||'')+(x.notes?' · '+esc(x.notes):'')+'</div></div><span class="badge">'+esc(x.status)+'</span></div><div class="row gap" style="margin-top:10px"><button class="secondary" onclick="editLead(\''+x.id+'\')">Edit</button><button class="secondary" onclick="openJobForLead(\''+x.id+'\')">Schedule Job</button></div></div>'}
function jobHTML(x){return '<div class="job"><div class="job-top"><div><strong>'+esc(x.title||x.name)+'</strong><div class="mutedline">'+esc(x.date||'No date')+' · '+esc(x.address||'')+'</div></div><span class="badge">'+esc(x.status||'Scheduled')+'</span></div></div>'}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
function openLead(existing){const x=existing||{status:'New',jobType:'Repair'};openModal('<h2>'+ (existing?'Edit':'New') +' Lead</h2><form id="leadForm"><div class="grid2"><label>Name<input name="name" required value="'+esc(x.name||'')+'"></label><label>Phone<input name="phone" value="'+esc(x.phone||'')+'"></label><label>Email<input name="email" value="'+esc(x.email||'')+'"></label><label>Address<input name="address" value="'+esc(x.address||'')+'"></label><label>Job type<select name="jobType">'+['Repair','Install','Staining','Removal'].map(o=>'<option '+(x.jobType===o?'selected':'')+'>'+o+'</option>').join('')+'</select></label><label>Status<select name="status">'+['New','Contacted','Estimate Scheduled','Estimate Sent','Won','Scheduled','Complete','Lost'].map(o=>'<option '+(x.status===o?'selected':'')+'>'+o+'</option>').join('')+'</select></label></div><label style="margin-top:14px">Notes<textarea name="notes" rows="4" style="background:#0b111b;color:#fff;border:1px solid var(--line);border-radius:9px;padding:12px">'+esc(x.notes||'')+'</textarea></label><div class="row form-actions"><button type="button" class="secondary" id="cancelModal">Cancel</button><button class="primary">Save Lead</button></div></form>');$('leadForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),obj=Object.fromEntries(fd);if(existing)Object.assign(existing,obj);else data.leads.unshift({id:crypto.randomUUID(),...obj,createdAt:new Date().toISOString()});save();closeModal();showView('leads')};$('cancelModal').onclick=closeModal}
function editLead(id){openLead(data.leads.find(x=>x.id===id))}function openJobForLead(id){openJob(data.leads.find(x=>x.id===id))}
function openJob(lead){const x={name:lead?.name||'',address:lead?.address||'',status:'Scheduled'};openModal('<h2>Schedule Job</h2><form id="jobForm"><div class="grid2"><label>Customer<input name="name" required value="'+esc(x.name)+'"></label><label>Date<input name="date" type="date" required></label><label>Address<input name="address" value="'+esc(x.address)+'"></label><label>Job status<select name="status"><option>Scheduled</option><option>In Progress</option><option>Complete</option></select></label><label>Job title<input name="title" value="'+esc(lead?.jobType||'Fence Job')+'"></label></div><div class="row form-actions"><button type="button" class="secondary" id="cancelModal">Cancel</button><button class="primary">Save Job</button></div></form>');$('jobForm').onsubmit=e=>{e.preventDefault();data.jobs.push({id:crypto.randomUUID(),...Object.fromEntries(new FormData(e.target))});if(lead&&lead.status==='Won')lead.status='Scheduled';save();closeModal();showView('jobs')};$('cancelModal').onclick=closeModal}
function calcEstimate(){const lf=+$('lf').value||0,posts=+$('posts').value||0,mat=+$('materialCost').value||0,h=+$('laborHours').value||0,rate=+$('laborRate').value||0,service=+$('serviceCharge').value||0,markup=(+$('markup').value||0)/100;const cost=mat+h*rate+service;const price=cost*(1+markup);$('estimateResult').innerHTML='<div class="muted">Customer quote</div><div class="estimate-price">'+money(price)+'</div><div class="profit">Estimated gross profit: '+money(price-cost)+'</div><div class="mutedline">'+lf+' LF · '+posts+' posts · Material billed at '+(mat?'selected material pricing':'$0.00')+' · Labor '+money(h*rate)+'</div>';return{lf,posts,mat,h,rate,service,markup,cost,price}}
['lf','posts','materialCost','laborHours','laborRate','serviceCharge','markup'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id)calcEstimate()}));document.addEventListener('change',e=>{if(e.target.id==='jobType')calcEstimate()});
document.addEventListener('click',e=>{const p=e.target.closest('[data-preset]');if(!p)return;const s=data.settings;if(p.dataset.preset==='post1'){$('posts').value=1;$('materialCost').value=s.woodPost14+s.quikrete*s.bagsPerPost}if(p.dataset.preset==='post5'){$('posts').value=5;$('materialCost').value=s.woodPost5*5+s.quikrete*s.bagsPerPost*5}if(p.dataset.preset==='repair'){$('lf').value=10;$('materialCost').value=50;$('laborHours').value=2}if(p.dataset.preset==='reinstall'){$('lf').value=20;$('materialCost').value=20;$('laborHours').value=2}calcEstimate()});
$('applyRepairPreset').onclick=()=>{$('jobType').value='Wood Repair';$('serviceCharge').value=data.settings.serviceCharge;$('laborRate').value=data.settings.laborRate;$('markup').value=35;calcEstimate()};
$('saveEstimate').onclick=()=>{const c=calcEstimate();data.estimates.unshift({id:crypto.randomUUID(),type:$('jobType').value,...c,createdAt:new Date().toISOString()});save();alert('Estimate saved.')};
$('leadSearch').oninput=renderLeads;$('leadFilter').onchange=renderLeads;
$('saveSettings').onclick=()=>{data.settings={...data.settings,laborRate:+$('defaultLaborRate').value,serviceCharge:+$('defaultServiceCharge').value,materialMarkup:+$('materialMarkup').value,homeDepotMarkup:+$('homeDepotMarkup').value,woodPost14:+$('woodPost14').value,woodPost5:+$('woodPost5').value,quikrete:+$('quikrete').value,bagsPerPost:+$('bagsPerPost').value,woodRepairLF:+$('woodRepairLF').value,reinstallLF:+$('reinstallLF').value,picketAmerican:+$('picketAmerican').value,railAmerican:+$('railAmerican').value,postAmerican:+$('postAmerican').value};save();alert('Pricing settings saved.')};
function renderJobs(){$('jobList').innerHTML=data.jobs.length?data.jobs.sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(jobHTML).join(''):'<div class="card"><p class="muted">No jobs scheduled.</p></div>'}
function renderSettings(){const s=data.settings;[['defaultLaborRate',s.laborRate],['defaultServiceCharge',s.serviceCharge],['materialMarkup',s.materialMarkup??25],['homeDepotMarkup',s.homeDepotMarkup??50],['woodPost14',s.woodPost14],['woodPost5',s.woodPost5],['quikrete',s.quikrete??10],['bagsPerPost',s.bagsPerPost],['woodRepairLF',s.woodRepairLF],['reinstallLF',s.reinstallLF],['picketAmerican',s.picketAmerican??8.21],['railAmerican',s.railAmerican??14.47],['postAmerican',s.postAmerican??48.69]].forEach(([id,v])=>$(id).value=v)}
function renderAll(){renderDashboard();renderLeads();renderJobs();renderSettings();calcEstimate()}$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='apex-fence-crm-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();alert('Backup imported.')}catch{alert('Invalid backup file.')}};r.readAsText(f)};
$('resetData').onclick=()=>{if(confirm('Delete all CRM data from this browser? Export a backup first if needed.')){data=structuredClone(defaultData);save()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
renderAll();